-- cervellone_scadenze: dedup degli eventi Google Calendar + guardia contro le
-- righe attive duplicate.
--
-- PERCHÉ (audit 17/08/2026 sul cablaggio scadenza→Calendar, commit 6634b10):
--
-- 1. Senza `calendar_event_id` non c'è modo di ritrovare l'evento creato per una
--    scadenza, quindi alla sostituzione il vecchio evento resta in agenda CON I
--    SUOI REMINDER: non è rumore visivo, è una notifica futura per una scadenza
--    che non esiste più. E la sostituzione è il flusso NOMINALE, non un caso
--    limite: il bot riepiloga e chiede conferma proprio perché la lettura di date
--    può sbagliare (prompts.ts), quindi ogni correzione di data produce un
--    fantasma. Dopo tre anni di rinnovi (DURC ogni 120 giorni, visita medica
--    ogni anno) un solo dipendente accumula ~9 eventi omonimi, tutti attivi.
--
-- 2. `marcaSostituite` è un read-modify-write non atomico su due round-trip
--    PostgREST. Due `registra_scadenza` concorrenti con la stessa chiave possono
--    marcare `sostituito` a vicenda la riga dell'altra e lasciare ZERO righe
--    attive — l'invariante che il fix di atomicità voleva rendere impossibile.
--    Il mutex per-chat del webhook Telegram serializza il caso normale, ma cede
--    dopo 150s di stale-lock, nel ramo degradato, e sugli entry point non-Telegram.
--
-- IDEMPOTENTE: si può rieseguire senza danno.

alter table public.cervellone_scadenze
  add column if not exists calendar_event_id text;

comment on column public.cervellone_scadenze.calendar_event_id is
  'ID evento Google Calendar creato da registra_scadenza. Serve a cancellare/aggiornare il vecchio evento quando la scadenza viene sostituita, invece di lasciarlo in agenda con i suoi reminder.';

-- ─────────────────────────────────────────────────────────────────────────────
-- INDICE UNICO: RIMOSSO DA QUESTA MIGRATION. NON aggiungerlo così com'è.
--
-- La prima stesura creava un indice unico parziale sulla chiave normalizzata
-- (soggetto, tipo_documento, categoria) fra le sole righe attive, per chiudere
-- la race di `marcaSostituite`. È INCOMPATIBILE con il codice in produzione, e
-- applicarlo romperebbe le registrazioni invece di proteggerle:
--
--   `registraScadenzaCore` fa **INSERT prima** e marca `sostituito` **dopo**
--   (scadenze-tools.ts). È l'ordine che chiude il P0 di perdita dati: se si
--   sostituisse prima e l'INSERT fallisse, la scadenza vecchia sarebbe già
--   morta e la nuova non esisterebbe.
--
--   Con l'indice attivo, ogni RINNOVO ha per un istante due righe attive con la
--   stessa chiave — la vecchia e la nuova appena inserita — quindi l'INSERT
--   viola l'unicità e il tool risponde "Errore inserimento scadenza": la
--   scadenza non verrebbe registrata affatto.
--
-- I due meccanismi si escludono a vicenda finché la scrittura resta su due
-- round-trip PostgREST separati. L'ordine INSERT-prima vale molto di più:
-- protegge da una perdita silenziosa, mentre l'indice proteggerebbe da una race
-- che richiede due registrazioni concorrenti sulla stessa chiave.
--
-- PER AVERE ENTRAMBI serve una RPC Postgres che faccia INSERT + UPDATE in
-- un'unica transazione (a quel punto l'unicità si può imporre, perché non
-- esiste più l'istante intermedio con due righe attive). È il lavoro giusto,
-- ma è un intervento a sé.
--
-- Utile comunque sapere se ci sono duplicati attivi già in tabella — probabile,
-- perché fino al 17/08/2026 il match su tipo_documento era case-sensitive e
-- 'DURC' vs 'Durc' non si sostituivano:
--
--   select lower(trim(soggetto))                    as sogg,
--          lower(trim(coalesce(tipo_documento,''))) as tipo,
--          lower(trim(coalesce(categoria,'')))      as cat,
--          count(*), array_agg(id order by created_at)
--   from public.cervellone_scadenze
--   where stato = 'attivo'
--   group by 1,2,3
--   having count(*) > 1;
--
-- Sono righe che oggi mandano promemoria doppi: vanno bonificate a mano
-- (tenere la più recente, portare le altre a stato='sostituito').
-- ─────────────────────────────────────────────────────────────────────────────
